# Generated by Django 3.1.6 on 2021-02-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default=' ', max_length=400),
            preserve_default=False,
        ),
    ]
